import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootWrappers from "@/components/wrappers/wrappers";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <RootWrappers>
          <Toaster
            position="bottom-right"
            toastOptions={{
              duration: 5000,
              unstyled: true,
              classNames: {
                toast: `
                    flex items-center gap-2
                    px-4 py-2 text-txt-primary w-100
                    bg-secondary shadow-outside-small rounded-3xl
                `,
              },
            }}
          />
          {children}

          <div id="modals"></div>
        </RootWrappers>
      </body>
    </html>
  );
}
