import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ViewModeSwitcher from "@/components/notes-view-mode/view-mode-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className="flex justify-center items-center gap-5">
          <Link href={"/"}>Home</Link>
          <Link href={"/notes"}>Notes</Link>
          <Link href={"/sign-up"}>Sign Up</Link>
          <Link href={"/sign-in"}>Sign In</Link>
          <ViewModeSwitcher />
        </div>
        {children}
        {modal}
        <div id="modals"></div>
      </body>
    </html>
  );
}
